USE idealcup;

-- 남자배우 (75명)
INSERT INTO contestant (name, category, image_path) VALUES
('강동원', '남자배우', '/images/contestants/남자배우/강동원.jpg'),
('강유석', '남자배우', '/images/contestants/남자배우/강유석.jpg'),
('강태오', '남자배우', '/images/contestants/남자배우/강태오.jpg'),
('강훈', '남자배우', '/images/contestants/남자배우/강훈.jpg'),
('고수', '남자배우', '/images/contestants/남자배우/고수.jpg'),
('공명', '남자배우', '/images/contestants/남자배우/공명.jpg'),
('공유', '남자배우', '/images/contestants/남자배우/공유.jpg'),
('곽동연', '남자배우', '/images/contestants/남자배우/곽동연.jpg'),
('구교환', '남자배우', '/images/contestants/남자배우/구교환.jpg'),
('김도훈', '남자배우', '/images/contestants/남자배우/김도훈.jpg'),
('김민규', '남자배우', '/images/contestants/남자배우/김민규.jpg'),
('김민재', '남자배우', '/images/contestants/남자배우/김민재.jpg'),
('김범', '남자배우', '/images/contestants/남자배우/김범.jpg'),
('김선호', '남자배우', '/images/contestants/남자배우/김선호.jpg'),
('김성철', '남자배우', '/images/contestants/남자배우/김성철.jpg'),
('김우빈', '남자배우', '/images/contestants/남자배우/김우빈.jpg'),
('김현진', '남자배우', '/images/contestants/남자배우/김현진.jpg'),
('나인우', '남자배우', '/images/contestants/남자배우/나인우.jpg'),
('남주혁', '남자배우', '/images/contestants/남자배우/남주혁.jpg'),
('도경수', '남자배우', '/images/contestants/남자배우/도경수.jpg'),
('로몬', '남자배우', '/images/contestants/남자배우/로몬.jpg'),
('로운', '남자배우', '/images/contestants/남자배우/로운.jpg'),
('문상민', '남자배우', '/images/contestants/남자배우/문상민.jpg'),
('박보검', '남자배우', '/images/contestants/남자배우/박보검.jpg'),
('박서준', '남자배우', '/images/contestants/남자배우/박서준.jpg'),
('박지훈', '남자배우', '/images/contestants/남자배우/박지훈.jpg'),
('박형식', '남자배우', '/images/contestants/남자배우/박형식.jpg'),
('배인혁', '남자배우', '/images/contestants/남자배우/배인혁.jpg'),
('변우석', '남자배우', '/images/contestants/남자배우/변우석.jpg'),
('서강준', '남자배우', '/images/contestants/남자배우/서강준.jpg'),
('서인국', '남자배우', '/images/contestants/남자배우/서인국.jpg'),
('소지섭', '남자배우', '/images/contestants/남자배우/소지섭.jpg'),
('송강', '남자배우', '/images/contestants/남자배우/송강.jpg'),
('송강호', '남자배우', '/images/contestants/남자배우/송강호.jpg'),
('송건희', '남자배우', '/images/contestants/남자배우/송건희.jpg'),
('송중기', '남자배우', '/images/contestants/남자배우/송중기.jpg'),
('신승호', '남자배우', '/images/contestants/남자배우/신승호.jpg'),
('안보현', '남자배우', '/images/contestants/남자배우/안보현.jpg'),
('안효섭', '남자배우', '/images/contestants/남자배우/안효섭.jpg'),
('양세종', '남자배우', '/images/contestants/남자배우/양세종.jpg'),
('여진구', '남자배우', '/images/contestants/남자배우/여진구.jpg'),
('우도환', '남자배우', '/images/contestants/남자배우/우도환.jpg'),
('원빈', '남자배우', '/images/contestants/남자배우/원빈.jpg'),
('유연석', '남자배우', '/images/contestants/남자배우/유연석.jpg'),
('육성재', '남자배우', '/images/contestants/남자배우/육성재.jpg'),
('이광수', '남자배우', '/images/contestants/남자배우/이광수.jpg'),
('이도현', '남자배우', '/images/contestants/남자배우/이도현.jpg'),
('이동욱', '남자배우', '/images/contestants/남자배우/이동욱.jpg'),
('이민기', '남자배우', '/images/contestants/남자배우/이민기.jpg'),
('이민호', '남자배우', '/images/contestants/남자배우/이민호.jpg'),
('이상엽', '남자배우', '/images/contestants/남자배우/이상엽.jpg'),
('이수혁', '남자배우', '/images/contestants/남자배우/이수혁.jpg'),
('이재욱', '남자배우', '/images/contestants/남자배우/이재욱.jpg'),
('이정하', '남자배우', '/images/contestants/남자배우/이정하.jpg'),
('이제훈', '남자배우', '/images/contestants/남자배우/이제훈.jpg'),
('이종석', '남자배우', '/images/contestants/남자배우/이종석.jpg'),
('이준영', '남자배우', '/images/contestants/남자배우/이준영.jpg'),
('이준혁', '남자배우', '/images/contestants/남자배우/이준혁.jpg'),
('이준호', '남자배우', '/images/contestants/남자배우/이준호.jpg'),
('이채민', '남자배우', '/images/contestants/남자배우/이채민.jpg'),
('임시완', '남자배우', '/images/contestants/남자배우/임시완.jpg'),
('장기용', '남자배우', '/images/contestants/남자배우/장기용.jpg'),
('장동윤', '남자배우', '/images/contestants/남자배우/장동윤.jpg'),
('정해인', '남자배우', '/images/contestants/남자배우/정해인.jpg'),
('지창욱', '남자배우', '/images/contestants/남자배우/지창욱.jpg'),
('진구', '남자배우', '/images/contestants/남자배우/진구.jpg'),
('차은우', '남자배우', '/images/contestants/남자배우/차은우.jpg'),
('채종협', '남자배우', '/images/contestants/남자배우/채종협.jpg'),
('최우식', '남자배우', '/images/contestants/남자배우/최우식.jpg'),
('최현욱', '남자배우', '/images/contestants/남자배우/최현욱.jpg'),
('추영우', '남자배우', '/images/contestants/남자배우/추영우.jpg'),
('현빈', '남자배우', '/images/contestants/남자배우/현빈.jpg'),
('황민현', '남자배우', '/images/contestants/남자배우/황민현.jpg');

-- 여자배우 (75명)
INSERT INTO contestant (name, category, image_path) VALUES
('강미나', '여자배우', '/images/contestants/여자배우/강미나.jpg'),
('강한나', '여자배우', '/images/contestants/여자배우/강한나.jpg'),
('고윤정', '여자배우', '/images/contestants/여자배우/고윤정.jpg'),
('김고은', '여자배우', '/images/contestants/여자배우/김고은.jpg'),
('김다미', '여자배우', '/images/contestants/여자배우/김다미.jpg'),
('김민주', '여자배우', '/images/contestants/여자배우/김민주.jpg'),
('김세정', '여자배우', '/images/contestants/여자배우/김세정.jpg'),
('김소현', '여자배우', '/images/contestants/여자배우/김소현.jpg'),
('김유정', '여자배우', '/images/contestants/여자배우/김유정.jpg'),
('김지원', '여자배우', '/images/contestants/여자배우/김지원.jpg'),
('김태리', '여자배우', '/images/contestants/여자배우/김태리.jpg'),
('김태희', '여자배우', '/images/contestants/여자배우/김태희.jpg'),
('나문희', '여자배우', '/images/contestants/여자배우/나문희.jpg'),
('남지현', '여자배우', '/images/contestants/여자배우/남지현.jpg'),
('노윤서', '여자배우', '/images/contestants/여자배우/노윤서.jpg'),
('노정의', '여자배우', '/images/contestants/여자배우/노정의.jpg'),
('문가영', '여자배우', '/images/contestants/여자배우/문가영.jpg'),
('문채원', '여자배우', '/images/contestants/여자배우/문채원.jpg'),
('박민영', '여자배우', '/images/contestants/여자배우/박민영.jpg'),
('박보영', '여자배우', '/images/contestants/여자배우/박보영.jpg'),
('박소담', '여자배우', '/images/contestants/여자배우/박소담.jpg'),
('박신혜', '여자배우', '/images/contestants/여자배우/박신혜.jpg'),
('박은빈', '여자배우', '/images/contestants/여자배우/박은빈.jpg'),
('박지현', '여자배우', '/images/contestants/여자배우/박지현.jpg'),
('박지후', '여자배우', '/images/contestants/여자배우/박지후.jpg'),
('서현진', '여자배우', '/images/contestants/여자배우/서현진.jpg'),
('설인아', '여자배우', '/images/contestants/여자배우/설인아.jpg'),
('소주연', '여자배우', '/images/contestants/여자배우/소주연.jpg'),
('송지효', '여자배우', '/images/contestants/여자배우/송지효.jpg'),
('송혜교', '여자배우', '/images/contestants/여자배우/송혜교.jpg'),
('수지', '여자배우', '/images/contestants/여자배우/수지.jpg'),
('신민아', '여자배우', '/images/contestants/여자배우/신민아.jpg'),
('신세경', '여자배우', '/images/contestants/여자배우/신세경.jpg'),
('신시아', '여자배우', '/images/contestants/여자배우/신시아.jpg'),
('신예은', '여자배우', '/images/contestants/여자배우/신예은.jpg'),
('신은수', '여자배우', '/images/contestants/여자배우/신은수.jpg'),
('신혜선', '여자배우', '/images/contestants/여자배우/신혜선.jpg'),
('안은진', '여자배우', '/images/contestants/여자배우/안은진.jpg'),
('연우', '여자배우', '/images/contestants/여자배우/연우.jpg'),
('유인나', '여자배우', '/images/contestants/여자배우/유인나.jpg'),
('윤아', '여자배우', '/images/contestants/여자배우/윤아.jpg'),
('이다희', '여자배우', '/images/contestants/여자배우/이다희.jpg'),
('이레', '여자배우', '/images/contestants/여자배우/이레.jpg'),
('이선빈', '여자배우', '/images/contestants/여자배우/이선빈.jpg'),
('이성경', '여자배우', '/images/contestants/여자배우/이성경.jpg'),
('이세영', '여자배우', '/images/contestants/여자배우/이세영.jpg'),
('이주빈', '여자배우', '/images/contestants/여자배우/이주빈.jpg'),
('이지은', '여자배우', '/images/contestants/여자배우/이지은.jpg'),
('임지연', '여자배우', '/images/contestants/여자배우/임지연.jpg'),
('장규리', '여자배우', '/images/contestants/여자배우/장규리.jpg'),
('장나라', '여자배우', '/images/contestants/여자배우/장나라.jpg'),
('전미도', '여자배우', '/images/contestants/여자배우/전미도.jpg'),
('전소민', '여자배우', '/images/contestants/여자배우/전소민.jpg'),
('전지현', '여자배우', '/images/contestants/여자배우/전지현.jpg'),
('정소민', '여자배우', '/images/contestants/여자배우/정소민.jpg'),
('정은지', '여자배우', '/images/contestants/여자배우/정은지.jpg'),
('정지소', '여자배우', '/images/contestants/여자배우/정지소.jpg'),
('정채연', '여자배우', '/images/contestants/여자배우/정채연.jpg'),
('조보아', '여자배우', '/images/contestants/여자배우/조보아.jpg'),
('조유리', '여자배우', '/images/contestants/여자배우/조유리.jpg'),
('조이현', '여자배우', '/images/contestants/여자배우/조이현.jpg'),
('주현영', '여자배우', '/images/contestants/여자배우/주현영.jpg'),
('지예은', '여자배우', '/images/contestants/여자배우/지예은.jpg'),
('진기주', '여자배우', '/images/contestants/여자배우/진기주.jpg'),
('차주영', '여자배우', '/images/contestants/여자배우/차주영.jpg'),
('채수빈', '여자배우', '/images/contestants/여자배우/채수빈.jpg'),
('채원빈', '여자배우', '/images/contestants/여자배우/채원빈.jpg'),
('천우희', '여자배우', '/images/contestants/여자배우/천우희.jpg'),
('최윤지', '여자배우', '/images/contestants/여자배우/최윤지.jpg'),
('하윤경', '여자배우', '/images/contestants/여자배우/하윤경.jpg'),
('한선화', '여자배우', '/images/contestants/여자배우/한선화.jpg'),
('한소희', '여자배우', '/images/contestants/여자배우/한소희.jpg'),
('한지민', '여자배우', '/images/contestants/여자배우/한지민.jpg'),
('한효주', '여자배우', '/images/contestants/여자배우/한효주.jpg'),
('혜리', '여자배우', '/images/contestants/여자배우/혜리.jpg');

-- 남자아이돌 (97명)
INSERT INTO contestant (name, category, image_path) VALUES
('갓세븐_진영', '남자아이돌', '/images/contestants/남자아이돌/갓세븐_진영.jpg'),
('고스트나인_이진우', '남자아이돌', '/images/contestants/남자아이돌/고스트나인_이진우.jpg'),
('더보이즈_영훈', '남자아이돌', '/images/contestants/남자아이돌/더보이즈_영훈.jpg'),
('데이식스_원필', '남자아이돌', '/images/contestants/남자아이돌/데이식스_원필.jpg'),
('드리핀_차준호', '남자아이돌', '/images/contestants/남자아이돌/드리핀_차준호.jpg'),
('라이즈_성찬', '남자아이돌', '/images/contestants/남자아이돌/라이즈_성찬.jpg'),
('라이즈_소희', '남자아이돌', '/images/contestants/남자아이돌/라이즈_소희.jpg'),
('라이즈_쇼타로', '남자아이돌', '/images/contestants/남자아이돌/라이즈_쇼타로.jpg'),
('라이즈_앤톤', '남자아이돌', '/images/contestants/남자아이돌/라이즈_앤톤.jpg'),
('라이즈_원빈', '남자아이돌', '/images/contestants/남자아이돌/라이즈_원빈.jpg'),
('라이즈_은석', '남자아이돌', '/images/contestants/남자아이돌/라이즈_은석.jpg'),
('루네이트_카엘', '남자아이돌', '/images/contestants/남자아이돌/루네이트_카엘.jpg'),
('방탄_뷔', '남자아이돌', '/images/contestants/남자아이돌/방탄_뷔.jpg'),
('방탄_슈가', '남자아이돌', '/images/contestants/남자아이돌/방탄_슈가.jpg'),
('방탄_알엠', '남자아이돌', '/images/contestants/남자아이돌/방탄_알엠.jpg'),
('방탄_정국', '남자아이돌', '/images/contestants/남자아이돌/방탄_정국.jpg'),
('방탄_제이홉', '남자아이돌', '/images/contestants/남자아이돌/방탄_제이홉.jpg'),
('방탄_진', '남자아이돌', '/images/contestants/남자아이돌/방탄_진.jpg'),
('베리베리_강민', '남자아이돌', '/images/contestants/남자아이돌/베리베리_강민.jpg'),
('보넥도_리우', '남자아이돌', '/images/contestants/남자아이돌/보넥도_리우.jpg'),
('보넥도_명재현', '남자아이돌', '/images/contestants/남자아이돌/보넥도_명재현.jpg'),
('보넥도_성호', '남자아이돌', '/images/contestants/남자아이돌/보넥도_성호.jpg'),
('보넥도_태산', '남자아이돌', '/images/contestants/남자아이돌/보넥도_태산.jpg'),
('블락비_피오', '남자아이돌', '/images/contestants/남자아이돌/블락비_피오.jpg'),
('샤이니_태민', '남자아이돌', '/images/contestants/남자아이돌/샤이니_태민.jpg'),
('세븐틴_도겸', '남자아이돌', '/images/contestants/남자아이돌/세븐틴_도겸.jpg'),
('스키즈_필릭스', '남자아이돌', '/images/contestants/남자아이돌/스키즈_필릭스.jpg'),
('아스트로_차은우', '남자아이돌', '/images/contestants/남자아이돌/아스트로_차은우.jpg'),
('아이콘_김진환', '남자아이돌', '/images/contestants/남자아이돌/아이콘_김진환.jpg'),
('아홉_차웅기', '남자아이돌', '/images/contestants/남자아이돌/아홉_차웅기.jpg'),
('알디원_이상원', '남자아이돌', '/images/contestants/남자아이돌/알디원_이상원.jpg'),
('앤팀_죠', '남자아이돌', '/images/contestants/남자아이돌/앤팀_죠.jpg'),
('앤팀_하루아', '남자아이돌', '/images/contestants/남자아이돌/앤팀_하루아.jpg'),
('에이티즈_최산', '남자아이돌', '/images/contestants/남자아이돌/에이티즈_최산.jpg'),
('엑디즈_가온', '남자아이돌', '/images/contestants/남자아이돌/엑디즈_가온.jpg'),
('엑디즈_오드', '남자아이돌', '/images/contestants/남자아이돌/엑디즈_오드.jpg'),
('엑디즈_주연', '남자아이돌', '/images/contestants/남자아이돌/엑디즈_주연.jpg'),
('엑소_세훈', '남자아이돌', '/images/contestants/남자아이돌/엑소_세훈.jpg'),
('엑소_수호', '남자아이돌', '/images/contestants/남자아이돌/엑소_수호.jpg'),
('엑소_카이', '남자아이돌', '/images/contestants/남자아이돌/엑소_카이.jpg'),
('엑스원_김우석', '남자아이돌', '/images/contestants/남자아이돌/엑스원_김우석.jpg'),
('엔시티127_도영', '남자아이돌', '/images/contestants/남자아이돌/엔시티127_도영.jpg'),
('엔시티127_재현', '남자아이돌', '/images/contestants/남자아이돌/엔시티127_재현.jpg'),
('엔시티127_정우', '남자아이돌', '/images/contestants/남자아이돌/엔시티127_정우.jpg'),
('엔시티127_태용', '남자아이돌', '/images/contestants/남자아이돌/엔시티127_태용.jpg'),
('엔시티드림_재민', '남자아이돌', '/images/contestants/남자아이돌/엔시티드림_재민.jpg'),
('엔시티드림_제노', '남자아이돌', '/images/contestants/남자아이돌/엔시티드림_제노.jpg'),
('엔시티드림_지성', '남자아이돌', '/images/contestants/남자아이돌/엔시티드림_지성.jpg'),
('엔시티위시_리쿠', '남자아이돌', '/images/contestants/남자아이돌/엔시티위시_리쿠.jpg'),
('엔시티위시_시온', '남자아이돌', '/images/contestants/남자아이돌/엔시티위시_시온.jpg'),
('엔시티위시_유우시', '남자아이돌', '/images/contestants/남자아이돌/엔시티위시_유우시.jpg'),
('엔하이픈_성훈', '남자아이돌', '/images/contestants/남자아이돌/엔하이픈_성훈.jpg'),
('엔하이픈_정원', '남자아이돌', '/images/contestants/남자아이돌/엔하이픈_정원.jpg'),
('엔하이픈_희승', '남자아이돌', '/images/contestants/남자아이돌/엔하이픈_희승.jpg'),
('올데프_우찬', '남자아이돌', '/images/contestants/남자아이돌/올데프_우찬.jpg'),
('올데프_타잔', '남자아이돌', '/images/contestants/남자아이돌/올데프_타잔.jpg'),
('우즈', '남자아이돌', '/images/contestants/남자아이돌/우즈.jpg'),
('워너원_박지훈', '남자아이돌', '/images/contestants/남자아이돌/워너원_박지훈.jpg'),
('워너원_옹성우', '남자아이돌', '/images/contestants/남자아이돌/워너원_옹성우.jpg'),
('워너원_황민현', '남자아이돌', '/images/contestants/남자아이돌/워너원_황민현.jpg'),
('웨이션브이_샤오쥔', '남자아이돌', '/images/contestants/남자아이돌/웨이션브이_샤오쥔.jpg'),
('이븐_이정현', '남자아이돌', '/images/contestants/남자아이돌/이븐_이정현.jpg'),
('인피니트_엘', '남자아이돌', '/images/contestants/남자아이돌/인피니트_엘.jpg'),
('장한음', '남자아이돌', '/images/contestants/남자아이돌/장한음.jpg'),
('제베원_성한빈', '남자아이돌', '/images/contestants/남자아이돌/제베원_성한빈.jpg'),
('제베원_장하오', '남자아이돌', '/images/contestants/남자아이돌/제베원_장하오.jpg'),
('제베원_한유진', '남자아이돌', '/images/contestants/남자아이돌/제베원_한유진.jpg'),
('코르티스_건호', '남자아이돌', '/images/contestants/남자아이돌/코르티스_건호.jpg'),
('코르티스_성현', '남자아이돌', '/images/contestants/남자아이돌/코르티스_성현.jpg'),
('코르티스_주훈', '남자아이돌', '/images/contestants/남자아이돌/코르티스_주훈.jpg'),
('크래비티_정모', '남자아이돌', '/images/contestants/남자아이돌/크래비티_정모.jpg'),
('크래비티_형준', '남자아이돌', '/images/contestants/남자아이돌/크래비티_형준.jpg'),
('템페스트_형섭', '남자아이돌', '/images/contestants/남자아이돌/템페스트_형섭.jpg'),
('투바투_범규', '남자아이돌', '/images/contestants/남자아이돌/투바투_범규.jpg'),
('투바투_수빈', '남자아이돌', '/images/contestants/남자아이돌/투바투_수빈.jpg'),
('투바투_연준', '남자아이돌', '/images/contestants/남자아이돌/투바투_연준.jpg'),
('투어스_도훈', '남자아이돌', '/images/contestants/남자아이돌/투어스_도훈.jpg'),
('투어스_신유', '남자아이돌', '/images/contestants/남자아이돌/투어스_신유.jpg'),
('트레저_하루토', '남자아이돌', '/images/contestants/남자아이돌/트레저_하루토.jpg'),
('플레이브_밤비', '남자아이돌', '/images/contestants/남자아이돌/플레이브_밤비.jpg'),
('피원하모니_인탁', '남자아이돌', '/images/contestants/남자아이돌/피원하모니_인탁.jpg'),
('피원하모니_테오', '남자아이돌', '/images/contestants/남자아이돌/피원하모니_테오.jpg'),
('휘브_이정', '남자아이돌', '/images/contestants/남자아이돌/휘브_이정.jpg');

-- 여자아이돌 (91명)
INSERT INTO contestant (name, category, image_path) VALUES
('권은비', '여자아이돌', '/images/contestants/여자아이돌/권은비.jpg'),
('뉴진스_민지', '여자아이돌', '/images/contestants/여자아이돌/뉴진스_민지.jpg'),
('뉴진스_하니', '여자아이돌', '/images/contestants/여자아이돌/뉴진스_하니.jpg'),
('뉴진스_해린', '여자아이돌', '/images/contestants/여자아이돌/뉴진스_해린.jpg'),
('뉴진스_혜인', '여자아이돌', '/images/contestants/여자아이돌/뉴진스_혜인.jpg'),
('라잇썸_초원', '여자아이돌', '/images/contestants/여자아이돌/라잇썸_초원.jpg'),
('레드벨벳_슬기', '여자아이돌', '/images/contestants/여자아이돌/레드벨벳_슬기.jpg'),
('레드벨벳_아이린', '여자아이돌', '/images/contestants/여자아이돌/레드벨벳_아이린.jpg'),
('레드벨벳_조이', '여자아이돌', '/images/contestants/여자아이돌/레드벨벳_조이.jpg'),
('르세라핌_김채원', '여자아이돌', '/images/contestants/여자아이돌/르세라핌_김채원.jpg'),
('르세라핌_카즈하', '여자아이돌', '/images/contestants/여자아이돌/르세라핌_카즈하.jpg'),
('르세라핌_허윤진', '여자아이돌', '/images/contestants/여자아이돌/르세라핌_허윤진.jpg'),
('르세라핌_홍은채', '여자아이돌', '/images/contestants/여자아이돌/르세라핌_홍은채.jpg'),
('미야오_안나', '여자아이돌', '/images/contestants/여자아이돌/미야오_안나.jpg'),
('베이비돈크라이_이현', '여자아이돌', '/images/contestants/여자아이돌/베이비돈크라이_이현.jpg'),
('베이비몬스터_로라', '여자아이돌', '/images/contestants/여자아이돌/베이비몬스터_로라.jpg'),
('베이비몬스터_아사', '여자아이돌', '/images/contestants/여자아이돌/베이비몬스터_아사.jpg'),
('베이비몬스터_아현', '여자아이돌', '/images/contestants/여자아이돌/베이비몬스터_아현.jpg'),
('블랙핑크_로제', '여자아이돌', '/images/contestants/여자아이돌/블랙핑크_로제.jpg'),
('블랙핑크_제니', '여자아이돌', '/images/contestants/여자아이돌/블랙핑크_제니.jpg'),
('비비지_신비', '여자아이돌', '/images/contestants/여자아이돌/비비지_신비.jpg'),
('비비지_은하', '여자아이돌', '/images/contestants/여자아이돌/비비지_은하.jpg'),
('빌리_츠키', '여자아이돌', '/images/contestants/여자아이돌/빌리_츠키.jpg'),
('세이마이네임_준휘', '여자아이돌', '/images/contestants/여자아이돌/세이마이네임_준휘.jpg'),
('소녀시대_태연', '여자아이돌', '/images/contestants/여자아이돌/소녀시대_태연.jpg'),
('스테이씨_아이사', '여자아이돌', '/images/contestants/여자아이돌/스테이씨_아이사.jpg'),
('스테이씨_윤', '여자아이돌', '/images/contestants/여자아이돌/스테이씨_윤.jpg'),
('아르테미스_희진', '여자아이돌', '/images/contestants/여자아이돌/아르테미스_희진.jpg'),
('아이들_미연', '여자아이돌', '/images/contestants/여자아이돌/아이들_미연.jpg'),
('아이들_민니', '여자아이돌', '/images/contestants/여자아이돌/아이들_민니.jpg'),
('아이들_슈화', '여자아이돌', '/images/contestants/여자아이돌/아이들_슈화.jpg'),
('아이브_가을', '여자아이돌', '/images/contestants/여자아이돌/아이브_가을.jpg'),
('아이브_레이', '여자아이돌', '/images/contestants/여자아이돌/아이브_레이.jpg'),
('아이브_리즈', '여자아이돌', '/images/contestants/여자아이돌/아이브_리즈.jpg'),
('아이브_안유진', '여자아이돌', '/images/contestants/여자아이돌/아이브_안유진.jpg'),
('아이브_이서', '여자아이돌', '/images/contestants/여자아이돌/아이브_이서.jpg'),
('아이브_장원영', '여자아이돌', '/images/contestants/여자아이돌/아이브_장원영.jpg'),
('아일릿_모카', '여자아이돌', '/images/contestants/여자아이돌/아일릿_모카.jpg'),
('아일릿_민주', '여자아이돌', '/images/contestants/여자아이돌/아일릿_민주.jpg'),
('아일릿_원희', '여자아이돌', '/images/contestants/여자아이돌/아일릿_원희.jpg'),
('에버글로우_시현', '여자아이돌', '/images/contestants/여자아이돌/에버글로우_시현.jpg'),
('에스파_닝닝', '여자아이돌', '/images/contestants/여자아이돌/에스파_닝닝.jpg'),
('에스파_윈터', '여자아이돌', '/images/contestants/여자아이돌/에스파_윈터.jpg'),
('에스파_지젤', '여자아이돌', '/images/contestants/여자아이돌/에스파_지젤.jpg'),
('에스파_카리나', '여자아이돌', '/images/contestants/여자아이돌/에스파_카리나.jpg'),
('에이프릴_이나은', '여자아이돌', '/images/contestants/여자아이돌/에이프릴_이나은.jpg'),
('에이핑크_손나은', '여자아이돌', '/images/contestants/여자아이돌/에이핑크_손나은.jpg'),
('에프엑스_크리스탈', '여자아이돌', '/images/contestants/여자아이돌/에프엑스_크리스탈.jpg'),
('엔믹스_규진', '여자아이돌', '/images/contestants/여자아이돌/엔믹스_규진.jpg'),
('엔믹스_설윤', '여자아이돌', '/images/contestants/여자아이돌/엔믹스_설윤.jpg'),
('오마이걸_아린', '여자아이돌', '/images/contestants/여자아이돌/오마이걸_아린.jpg'),
('올데프_애니', '여자아이돌', '/images/contestants/여자아이돌/올데프_애니.jpg'),
('올데프_영서', '여자아이돌', '/images/contestants/여자아이돌/올데프_영서.jpg'),
('우아_나나', '여자아이돌', '/images/contestants/여자아이돌/우아_나나.jpg'),
('우주소녀_보나', '여자아이돌', '/images/contestants/여자아이돌/우주소녀_보나.jpg'),
('우주소녀_설아', '여자아이돌', '/images/contestants/여자아이돌/우주소녀_설아.jpg'),
('위키미키_김도연', '여자아이돌', '/images/contestants/여자아이돌/위키미키_김도연.jpg'),
('위키미키_최유정', '여자아이돌', '/images/contestants/여자아이돌/위키미키_최유정.jpg'),
('이즈나_방지민', '여자아이돌', '/images/contestants/여자아이돌/이즈나_방지민.jpg'),
('이즈나_유사랑', '여자아이돌', '/images/contestants/여자아이돌/이즈나_유사랑.jpg'),
('이즈나_정세비', '여자아이돌', '/images/contestants/여자아이돌/이즈나_정세비.jpg'),
('있지_예지', '여자아이돌', '/images/contestants/여자아이돌/있지_예지.jpg'),
('있지_유나', '여자아이돌', '/images/contestants/여자아이돌/있지_유나.jpg'),
('최예나', '여자아이돌', '/images/contestants/여자아이돌/최예나.jpg'),
('캣츠아이_윤채', '여자아이돌', '/images/contestants/여자아이돌/캣츠아이_윤채.jpg'),
('케플러_김채현', '여자아이돌', '/images/contestants/여자아이돌/케플러_김채현.jpg'),
('케플러_샤오팅', '여자아이돌', '/images/contestants/여자아이돌/케플러_샤오팅.jpg'),
('키오프_쥴리', '여자아이돌', '/images/contestants/여자아이돌/키오프_쥴리.jpg'),
('키오프_하늘', '여자아이돌', '/images/contestants/여자아이돌/키오프_하늘.jpg'),
('키키_이솔', '여자아이돌', '/images/contestants/여자아이돌/키키_이솔.jpg'),
('키키_하음', '여자아이돌', '/images/contestants/여자아이돌/키키_하음.jpg'),
('트리플에스_김유연', '여자아이돌', '/images/contestants/여자아이돌/트리플에스_김유연.jpg'),
('트와이스_나연', '여자아이돌', '/images/contestants/여자아이돌/트와이스_나연.jpg'),
('트와이스_사나', '여자아이돌', '/images/contestants/여자아이돌/트와이스_사나.jpg'),
('트와이스_쯔위', '여자아이돌', '/images/contestants/여자아이돌/트와이스_쯔위.jpg'),
('티아라_함은정', '여자아이돌', '/images/contestants/여자아이돌/티아라_함은정.jpg'),
('프로미스나인_백지헌', '여자아이돌', '/images/contestants/여자아이돌/프로미스나인_백지헌.jpg'),
('프로미스나인_송하영', '여자아이돌', '/images/contestants/여자아이돌/프로미스나인_송하영.jpg'),
('프로미스나인_이채영', '여자아이돌', '/images/contestants/여자아이돌/프로미스나인_이채영.jpg'),
('피프티피프티_문샤넬', '여자아이돌', '/images/contestants/여자아이돌/피프티피프티_문샤넬.jpg'),
('피프티피프티_하나', '여자아이돌', '/images/contestants/여자아이돌/피프티피프티_하나.jpg'),
('하투하_이안', '여자아이돌', '/images/contestants/여자아이돌/하투하_이안.jpg'),
('하투하_지우', '여자아이돌', '/images/contestants/여자아이돌/하투하_지우.jpg');

-- 드라마 (64개)
INSERT INTO contestant (name, category, image_path) VALUES
('구르미 그린 달빛', '드라마', '/images/contestants/OST/구르미 그린 달빛.jpg'),
('궁', '드라마', '/images/contestants/OST/궁.jpg'),
('그해 우리는', '드라마', '/images/contestants/OST/그해 우리는.jpg'),
('김비서가 왜 그럴까', '드라마', '/images/contestants/OST/김비서가 왜 그럴까.jpg'),
('꽃보다 남자', '드라마', '/images/contestants/OST/꽃보다 남자.jpg'),
('나쁜 엄마', '드라마', '/images/contestants/OST/나쁜 엄마.jpg'),
('나의 아저씨', '드라마', '/images/contestants/OST/나의 아저씨.jpg'),
('낭만닥터 김사부', '드라마', '/images/contestants/OST/낭만닥터 김사부.jpg'),
('눈물의 여왕', '드라마', '/images/contestants/OST/눈물의 여왕.jpg'),
('다 이루어질지니', '드라마', '/images/contestants/OST/다 이루어질지니.jpg'),
('달의 연인', '드라마', '/images/contestants/OST/달의 연인.jpg'),
('더 글로리', '드라마', '/images/contestants/OST/더 글로리.jpg'),
('도깨비', '드라마', '/images/contestants/OST/도깨비.jpg'),
('동백꽃 필 무렵', '드라마', '/images/contestants/OST/동백꽃 필 무렵.jpg'),
('드림하이', '드라마', '/images/contestants/OST/드림하이.jpg'),
('마이데몬', '드라마', '/images/contestants/OST/마이데몬.jpg'),
('멜로가 체질', '드라마', '/images/contestants/OST/멜로가 체질.jpg'),
('무빙', '드라마', '/images/contestants/OST/무빙.jpg'),
('미스터 션샤인', '드라마', '/images/contestants/OST/미스터 션샤인.jpg'),
('미안하다 사랑한다', '드라마', '/images/contestants/OST/미안하다 사랑한다.jpg'),
('반짝이는 워터멜론', '드라마', '/images/contestants/OST/반짝이는 워터멜론.jpg'),
('백일의 낭군님', '드라마', '/images/contestants/OST/백일의 낭군님.jpg'),
('별에서 온 그대', '드라마', '/images/contestants/OST/별에서 온 그대.jpg'),
('사내맞선', '드라마', '/images/contestants/OST/사내맞선.jpg'),
('사랑의 불시착', '드라마', '/images/contestants/OST/사랑의 불시착.jpg'),
('상속자들', '드라마', '/images/contestants/OST/상속자들.jpg'),
('선재 업고 튀어', '드라마', '/images/contestants/OST/선재 업고 튀어.jpg'),
('소용없어 거짓말', '드라마', '/images/contestants/OST/소용없어 거짓말.jpg'),
('스물다섯 스물하나', '드라마', '/images/contestants/OST/스물다섯 스물하나.jpg'),
('스위트홈', '드라마', '/images/contestants/OST/스위트홈.jpg'),
('스타트업', '드라마', '/images/contestants/OST/스타트업.jpg'),
('슬기로운 의사생활', '드라마', '/images/contestants/OST/슬기로운 의사생활.jpg'),
('시크릿 가든', '드라마', '/images/contestants/OST/시크릿 가든.jpg'),
('쌈, 마이웨이', '드라마', '/images/contestants/OST/쌈, 마이웨이.jpg'),
('약한영웅', '드라마', '/images/contestants/OST/약한영웅.jpg'),
('어쩌다 발견한 하루', '드라마', '/images/contestants/OST/어쩌다 발견한 하루.jpg'),
('언젠가는 슬기로울 전공의 생활', '드라마', '/images/contestants/OST/언젠가는 슬기로울 전공의 생활.jpg'),
('엄마친구아들', '드라마', '/images/contestants/OST/엄마친구아들.jpg'),
('에이틴', '드라마', '/images/contestants/OST/에이틴.jpg'),
('여신강림', '드라마', '/images/contestants/OST/여신강림.jpg'),
('역도요정 김복주', '드라마', '/images/contestants/OST/역도요정 김복주.jpg'),
('오월의 청춘', '드라마', '/images/contestants/OST/오월의 청춘.jpg'),
('오징어게임', '드라마', '/images/contestants/OST/오징어게임.jpg'),
('우리들의 블루스', '드라마', '/images/contestants/OST/우리들의 블루스.jpg'),
('웰컴 투 삼달리', '드라마', '/images/contestants/OST/웰컴 투 삼달리.jpg'),
('응답하라 1988', '드라마', '/images/contestants/OST/응답하라 1988.jpg'),
('이상한 변호사 우영우', '드라마', '/images/contestants/OST/이상한 변호사 우영우.jpg'),
('이태원 클라쓰', '드라마', '/images/contestants/OST/이태원 클라쓰.jpg'),
('재벌집 막내아들', '드라마', '/images/contestants/OST/재벌집 막내아들.jpg'),
('정년이', '드라마', '/images/contestants/OST/정년이.jpg'),
('중증외상센터', '드라마', '/images/contestants/OST/중증외상센터.jpg'),
('지금 우리 학교는', '드라마', '/images/contestants/OST/지금 우리 학교는.jpg'),
('철인왕후', '드라마', '/images/contestants/OST/철인왕후.jpg'),
('커피프린스 1호점', '드라마', '/images/contestants/OST/커피프린스 1호점.jpg'),
('태양의 후예', '드라마', '/images/contestants/OST/태양의 후예.jpg'),
('파리의 연인', '드라마', '/images/contestants/OST/파리의 연인.jpg'),
('펜트하우스', '드라마', '/images/contestants/OST/펜트하우스.jpg'),
('폭싹 속았수다', '드라마', '/images/contestants/OST/폭싹 속았수다.jpg'),
('피라미드 게임', '드라마', '/images/contestants/OST/피라미드 게임.jpg'),
('하이쿠키', '드라마', '/images/contestants/OST/하이쿠키.jpg'),
('학교 2015 - 후아유', '드라마', '/images/contestants/OST/학교 2015 - 후아유.jpg'),
('호텔 델루나', '드라마', '/images/contestants/OST/호텔 델루나.jpg'),
('환혼', '드라마', '/images/contestants/OST/환혼.jpg'),
('힘쎈여자 도봉순', '드라마', '/images/contestants/OST/힘쎈여자 도봉순.jpg');

-- 음식 (70개)
INSERT INTO contestant (name, category, image_path) VALUES
('LA갈비', '음식', '/images/contestants/음식/LA갈비.jpg'),
('간장게장', '음식', '/images/contestants/음식/간장게장.jpg'),
('갈치조림', '음식', '/images/contestants/음식/갈치조림.jpg'),
('감자탕', '음식', '/images/contestants/음식/감자탕.jpg'),
('곱창', '음식', '/images/contestants/음식/곱창.jpg'),
('규동', '음식', '/images/contestants/음식/규동.jpg'),
('김밥', '음식', '/images/contestants/음식/김밥.jpg'),
('김치볶음밥', '음식', '/images/contestants/음식/김치볶음밥.jpg'),
('김치찌개', '음식', '/images/contestants/음식/김치찌개.jpg'),
('김치찜', '음식', '/images/contestants/음식/김치찜.jpg'),
('꿔바로우', '음식', '/images/contestants/음식/꿔바로우.jpg'),
('냉면', '음식', '/images/contestants/음식/냉면.jpg'),
('닭갈비', '음식', '/images/contestants/음식/닭갈비.jpg'),
('닭강정', '음식', '/images/contestants/음식/닭강정.jpg'),
('닭발', '음식', '/images/contestants/음식/닭발.jpg'),
('대게', '음식', '/images/contestants/음식/대게.jpg'),
('도넛', '음식', '/images/contestants/음식/도넛.jpg'),
('돈까스', '음식', '/images/contestants/음식/돈까스.jpg'),
('돼지국밥', '음식', '/images/contestants/음식/돼지국밥.jpg'),
('된장찌개', '음식', '/images/contestants/음식/된장찌개.jpg'),
('라면', '음식', '/images/contestants/음식/라면.jpg'),
('랍스터', '음식', '/images/contestants/음식/랍스터.jpg'),
('마라샹궈', '음식', '/images/contestants/음식/마라샹궈.jpg'),
('마라탕', '음식', '/images/contestants/음식/마라탕.jpg'),
('마제소바', '음식', '/images/contestants/음식/마제소바.jpg'),
('마파두부', '음식', '/images/contestants/음식/마파두부.jpg'),
('막창', '음식', '/images/contestants/음식/막창.jpg'),
('만두', '음식', '/images/contestants/음식/만두.jpg'),
('보쌈', '음식', '/images/contestants/음식/보쌈.jpg'),
('부대찌개', '음식', '/images/contestants/음식/부대찌개.jpg'),
('비빔밥', '음식', '/images/contestants/음식/비빔밥.jpg'),
('삼겹살', '음식', '/images/contestants/음식/삼겹살.jpg'),
('새우', '음식', '/images/contestants/음식/새우.jpg'),
('샌드위치', '음식', '/images/contestants/음식/샌드위치.jpg'),
('샤브샤브', '음식', '/images/contestants/음식/샤브샤브.jpg'),
('설렁탕', '음식', '/images/contestants/음식/설렁탕.jpg'),
('수제비', '음식', '/images/contestants/음식/수제비.jpg'),
('순두부', '음식', '/images/contestants/음식/순두부.jpg'),
('스테이크', '음식', '/images/contestants/음식/스테이크.jpg'),
('쌀국수', '음식', '/images/contestants/음식/쌀국수.jpg'),
('아구찜', '음식', '/images/contestants/음식/아구찜.jpg'),
('양꼬치', '음식', '/images/contestants/음식/양꼬치.jpg'),
('양념게장', '음식', '/images/contestants/음식/양념게장.jpg'),
('엽떡', '음식', '/images/contestants/음식/엽떡.jpg'),
('오믈렛', '음식', '/images/contestants/음식/오믈렛.jpg'),
('우동', '음식', '/images/contestants/음식/우동.jpg'),
('육회', '음식', '/images/contestants/음식/육회.jpg'),
('잔치국수', '음식', '/images/contestants/음식/잔치국수.jpg'),
('장어', '음식', '/images/contestants/음식/장어.jpg'),
('장칼국수', '음식', '/images/contestants/음식/장칼국수.jpg'),
('제육볶음', '음식', '/images/contestants/음식/제육볶음.jpg'),
('족발', '음식', '/images/contestants/음식/족발.jpg'),
('짜장면', '음식', '/images/contestants/음식/짜장면.jpg'),
('짬뽕', '음식', '/images/contestants/음식/짬뽕.jpg'),
('찜닭', '음식', '/images/contestants/음식/찜닭.jpg'),
('차돌박이', '음식', '/images/contestants/음식/차돌박이.jpg'),
('초밥', '음식', '/images/contestants/음식/초밥.jpg'),
('추어탕', '음식', '/images/contestants/음식/추어탕.jpg'),
('치킨', '음식', '/images/contestants/음식/치킨.jpg'),
('치킨누들수프', '음식', '/images/contestants/음식/치킨누들수프.jpg'),
('칼국수', '음식', '/images/contestants/음식/칼국수.jpg'),
('타코', '음식', '/images/contestants/음식/타코.jpg'),
('탕수육', '음식', '/images/contestants/음식/탕수육.jpg'),
('텐동', '음식', '/images/contestants/음식/텐동.jpg'),
('파스타', '음식', '/images/contestants/음식/파스타.jpg'),
('팬케이크', '음식', '/images/contestants/음식/팬케이크.jpg'),
('피시앤칩스', '음식', '/images/contestants/음식/피시앤칩스.jpg'),
('피자', '음식', '/images/contestants/음식/피자.jpg'),
('핫도그', '음식', '/images/contestants/음식/핫도그.jpg'),
('햄버거', '음식', '/images/contestants/음식/햄버거.jpg'),
('회', '음식', '/images/contestants/음식/회.jpg'),
('훠궈', '음식', '/images/contestants/음식/훠궈.jpg');

-- 여행지 (57개)
INSERT INTO contestant (name, category, image_path) VALUES
('LA', '여행지', '/images/contestants/여행지/LA.jpg'),
('가평', '여행지', '/images/contestants/여행지/가평.jpg'),
('경주', '여행지', '/images/contestants/여행지/경주.jpg'),
('괌', '여행지', '/images/contestants/여행지/괌.jpg'),
('그랜드캐니언', '여행지', '/images/contestants/여행지/그랜드캐니언.jpg'),
('나이아가라폭포', '여행지', '/images/contestants/여행지/나이아가라폭포.jpg'),
('나트랑', '여행지', '/images/contestants/여행지/나트랑.jpg'),
('뉴욕', '여행지', '/images/contestants/여행지/뉴욕.jpg'),
('도쿄', '여행지', '/images/contestants/여행지/도쿄.jpg'),
('두바이', '여행지', '/images/contestants/여행지/두바이.jpg'),
('라스베가스', '여행지', '/images/contestants/여행지/라스베가스.jpg'),
('런던', '여행지', '/images/contestants/여행지/런던.jpg'),
('로마', '여행지', '/images/contestants/여행지/로마.jpg'),
('리스본', '여행지', '/images/contestants/여행지/리스본.jpg'),
('리우데자네이루', '여행지', '/images/contestants/여행지/리우데자네이루.jpg'),
('마드리드', '여행지', '/images/contestants/여행지/마드리드.jpg'),
('마이애미', '여행지', '/images/contestants/여행지/마이애미.jpg'),
('마카오', '여행지', '/images/contestants/여행지/마카오.jpg'),
('멕시코시티', '여행지', '/images/contestants/여행지/멕시코시티.jpg'),
('몰디브', '여행지', '/images/contestants/여행지/몰디브.jpg'),
('밀라노', '여행지', '/images/contestants/여행지/밀라노.jpg'),
('발리', '여행지', '/images/contestants/여행지/발리.jpg'),
('방콕', '여행지', '/images/contestants/여행지/방콕.jpg'),
('베네치아', '여행지', '/images/contestants/여행지/베네치아.jpg'),
('베이징', '여행지', '/images/contestants/여행지/베이징.jpg'),
('부다페스트', '여행지', '/images/contestants/여행지/부다페스트.jpg'),
('부산', '여행지', '/images/contestants/여행지/부산.jpg'),
('브뤼셀', '여행지', '/images/contestants/여행지/브뤼셀.jpg'),
('빈', '여행지', '/images/contestants/여행지/빈.jpg'),
('산토리니', '여행지', '/images/contestants/여행지/산토리니.jpg'),
('삿포로', '여행지', '/images/contestants/여행지/삿포로.jpg'),
('상하이', '여행지', '/images/contestants/여행지/상하이.jpg'),
('서울', '여행지', '/images/contestants/여행지/서울.jpg'),
('세부', '여행지', '/images/contestants/여행지/세부.jpg'),
('속초', '여행지', '/images/contestants/여행지/속초.jpg'),
('시드니', '여행지', '/images/contestants/여행지/시드니.jpg'),
('시카고', '여행지', '/images/contestants/여행지/시카고.jpg'),
('싱가포르', '여행지', '/images/contestants/여행지/싱가포르.jpg'),
('아이슬란드', '여행지', '/images/contestants/여행지/아이슬란드.jpg'),
('알프스', '여행지', '/images/contestants/여행지/알프스.jpg'),
('암스테르담', '여행지', '/images/contestants/여행지/암스테르담.jpg'),
('오사카', '여행지', '/images/contestants/여행지/오사카.jpg'),
('요코하마', '여행지', '/images/contestants/여행지/요코하마.jpg'),
('우유니소금사막', '여행지', '/images/contestants/여행지/우유니소금사막.jpg'),
('울릉도', '여행지', '/images/contestants/여행지/울릉도.jpg'),
('제주도', '여행지', '/images/contestants/여행지/제주도.jpg'),
('카이로', '여행지', '/images/contestants/여행지/카이로.jpg'),
('코타키나발루', '여행지', '/images/contestants/여행지/코타키나발루.jpg'),
('코펜하겐', '여행지', '/images/contestants/여행지/코펜하겐.jpg'),
('파리', '여행지', '/images/contestants/여행지/파리.jpg'),
('프라하', '여행지', '/images/contestants/여행지/프라하.jpg'),
('하와이', '여행지', '/images/contestants/여행지/하와이.jpg'),
('홍콩', '여행지', '/images/contestants/여행지/홍콩.jpg');

-- 애니메이션 (60개)
INSERT INTO contestant (name, category, image_path) VALUES
('겨울왕국', '애니메이션', '/images/contestants/애니메이션/겨울왕국.jpg'),
('귀멸의 칼날', '애니메이션', '/images/contestants/애니메이션/귀멸의 칼날.jpg'),
('꿈빛파티시엘', '애니메이션', '/images/contestants/애니메이션/꿈빛파티시엘.jpg'),
('나 혼자만 레벨업', '애니메이션', '/images/contestants/애니메이션/나 혼자만 레벨업.jpg'),
('나루토', '애니메이션', '/images/contestants/애니메이션/나루토.jpg'),
('나의 히어로 아카데미아', '애니메이션', '/images/contestants/애니메이션/나의 히어로 아카데미아.jpg'),
('너에게 닿기를', '애니메이션', '/images/contestants/애니메이션/너에게 닿기를.jpg'),
('너의 이름은', '애니메이션', '/images/contestants/애니메이션/너의 이름은.jpg'),
('네모바지 스폰지밥', '애니메이션', '/images/contestants/애니메이션/네모바지 스폰지밥.jpg'),
('도라에몽', '애니메이션', '/images/contestants/애니메이션/도라에몽.jpg'),
('도쿄 구울', '애니메이션', '/images/contestants/애니메이션/도쿄 구울.jpg'),
('드래곤 길들이기', '애니메이션', '/images/contestants/애니메이션/드래곤 길들이기.jpg'),
('드래곤볼', '애니메이션', '/images/contestants/애니메이션/드래곤볼.jpg'),
('또봇', '애니메이션', '/images/contestants/애니메이션/또봇.jpg'),
('레이디버그', '애니메이션', '/images/contestants/애니메이션/레이디버그.jpg'),
('명탐정 코난', '애니메이션', '/images/contestants/애니메이션/명탐정 코난.jpg'),
('몬스터 주식회사', '애니메이션', '/images/contestants/애니메이션/몬스터 주식회사.jpg'),
('바다 탐험대 옥토넛', '애니메이션', '/images/contestants/애니메이션/바다 탐험대 옥토넛.jpg'),
('브레드 이발소', '애니메이션', '/images/contestants/애니메이션/브레드 이발소.jpg'),
('블루 록', '애니메이션', '/images/contestants/애니메이션/블루 록.jpg'),
('뽀롱뽀롱 뽀로로', '애니메이션', '/images/contestants/애니메이션/뽀롱뽀롱 뽀로로.jpg'),
('센과 치히로의 행방불명', '애니메이션', '/images/contestants/애니메이션/센과 치히로의 행방불명.jpg'),
('슈가슈가룬', '애니메이션', '/images/contestants/애니메이션/슈가슈가룬.jpg'),
('스즈메의 문단속', '애니메이션', '/images/contestants/애니메이션/스즈메의 문단속.jpg'),
('스파이패밀리', '애니메이션', '/images/contestants/애니메이션/스파이패밀리.jpg'),
('슬램덩크', '애니메이션', '/images/contestants/애니메이션/슬램덩크.jpg'),
('시크릿 쥬쥬', '애니메이션', '/images/contestants/애니메이션/시크릿 쥬쥬.jpg'),
('신비아파트', '애니메이션', '/images/contestants/애니메이션/신비아파트.jpg'),
('아기공룡 둘리', '애니메이션', '/images/contestants/애니메이션/아기공룡 둘리.jpg'),
('아따맘마', '애니메이션', '/images/contestants/애니메이션/아따맘마.jpg'),
('아이엠스타', '애니메이션', '/images/contestants/애니메이션/아이엠스타.jpg'),
('안녕 자두야', '애니메이션', '/images/contestants/애니메이션/안녕 자두야.jpg'),
('엘리멘탈', '애니메이션', '/images/contestants/애니메이션/엘리멘탈.jpg'),
('요괴워치', '애니메이션', '/images/contestants/애니메이션/요괴워치.jpg'),
('원피스', '애니메이션', '/images/contestants/애니메이션/원피스.jpg'),
('이누야샤', '애니메이션', '/images/contestants/애니메이션/이누야샤.jpg'),
('이웃집 토토로', '애니메이션', '/images/contestants/애니메이션/이웃집 토토로.jpg'),
('인사이드 아웃', '애니메이션', '/images/contestants/애니메이션/인사이드 아웃.jpg'),
('주술회전', '애니메이션', '/images/contestants/애니메이션/주술회전.jpg'),
('주토피아', '애니메이션', '/images/contestants/애니메이션/주토피아.jpg'),
('진격의 거인', '애니메이션', '/images/contestants/애니메이션/진격의 거인.jpg'),
('짱구는 못 말려', '애니메이션', '/images/contestants/애니메이션/짱구는 못 말려.jpg'),
('체인소맨', '애니메이션', '/images/contestants/애니메이션/체인소맨.jpg'),
('최애의 아이', '애니메이션', '/images/contestants/애니메이션/최애의 아이.jpg'),
('캐릭캐릭체인지', '애니메이션', '/images/contestants/애니메이션/캐릭캐릭체인지.jpg'),
('캐치 티니핑', '애니메이션', '/images/contestants/애니메이션/캐치 티니핑.jpg'),
('케이팝 데몬 헌터스', '애니메이션', '/images/contestants/애니메이션/케이팝 데몬 헌터스.jpg'),
('코코', '애니메이션', '/images/contestants/애니메이션/코코.jpg'),
('터닝메카드', '애니메이션', '/images/contestants/애니메이션/터닝메카드.jpg'),
('토이스토리', '애니메이션', '/images/contestants/애니메이션/토이스토리.jpg'),
('톰과 제리', '애니메이션', '/images/contestants/애니메이션/톰과 제리.jpg'),
('트롤', '애니메이션', '/images/contestants/애니메이션/트롤.jpg'),
('포켓몬스터', '애니메이션', '/images/contestants/애니메이션/포켓몬스터.jpg'),
('하울의 움직이는 성', '애니메이션', '/images/contestants/애니메이션/하울의 움직이는 성.jpg'),
('하이큐', '애니메이션', '/images/contestants/애니메이션/하이큐.jpg'),
('헬로카봇', '애니메이션', '/images/contestants/애니메이션/헬로카봇.jpg');